import type { KeyboardButton } from "../../../utility/types";

export const keyboardRows: KeyboardButton[][] = [
  [
    { key: '`', keyCode: 'Backquote' },
    { key: '1', keyCode: 'Digit1' },
    { key: '2', keyCode: 'Digit2' },
    { key: '3', keyCode: 'Digit3' },
    { key: '4', keyCode: 'Digit4' },
    { key: '5', keyCode: 'Digit5' },
    { key: '6', keyCode: 'Digit6' },
    { key: '7', keyCode: 'Digit7' },
    { key: '8', keyCode: 'Digit8' },
    { key: '9', keyCode: 'Digit9' },
    { key: '0', keyCode: 'Digit0' },
    { key: '-', keyCode: 'Minus' },
    { key: '=', keyCode: 'Equal' },
    { key: 'Backspace', keyCode: 'Backspace', width: 'large' },
  ],
  [
    { key: 'Tab', keyCode: 'Tab', width: 'medium' },
    { key: 'Q', keyCode: 'KeyQ' },
    { key: 'W', keyCode: 'KeyW' },
    { key: 'E', keyCode: 'KeyE' },
    { key: 'R', keyCode: 'KeyR' },
    { key: 'T', keyCode: 'KeyT' },
    { key: 'Y', keyCode: 'KeyY' },
    { key: 'U', keyCode: 'KeyU' },
    { key: 'I', keyCode: 'KeyI' },
    { key: 'O', keyCode: 'KeyO' },
    { key: 'P', keyCode: 'KeyP' },
    { key: '[', keyCode: 'BracketLeft' },
    { key: ']', keyCode: 'BracketRight' },
    { key: '\\', keyCode: 'Backslash' },
  ],
  [
    { key: 'Caps', keyCode: 'CapsLock', width: 'large' },
    { key: 'A', keyCode: 'KeyA' },
    { key: 'S', keyCode: 'KeyS' },
    { key: 'D', keyCode: 'KeyD' },
    { key: 'F', keyCode: 'KeyF', anchor: true },
    { key: 'G', keyCode: 'KeyG' },
    { key: 'H', keyCode: 'KeyH' },
    { key: 'J', keyCode: 'KeyJ', anchor: true },
    { key: 'K', keyCode: 'KeyK' },
    { key: 'L', keyCode: 'KeyL' },
    { key: ';', keyCode: 'Semicolon' },
    { key: "'", keyCode: 'Quote' },
    { key: 'Enter', keyCode: 'Enter', width: 'large' },
  ],
  [
    { key: 'Shift', keyCode: 'ShiftLeft', width: 'xlarge' },
    { key: 'Z', keyCode: 'KeyZ' },
    { key: 'X', keyCode: 'KeyX' },
    { key: 'C', keyCode: 'KeyC' },
    { key: 'V', keyCode: 'KeyV' },
    { key: 'B', keyCode: 'KeyB' },
    { key: 'N', keyCode: 'KeyN' },
    { key: 'M', keyCode: 'KeyM' },
    { key: ',', keyCode: 'Comma' },
    { key: '.', keyCode: 'Period' },
    { key: '/', keyCode: 'Slash' },
    { key: 'Shift', keyCode: 'ShiftRight', width: 'xlarge' },
  ],
  [
    { key: 'Space', keyCode: 'Space', width: 'space' },
  ],
];