export const keyboardRows = [
  [
    { key: '`' },
    { key: '1' },
    { key: '2' },
    { key: '3' },
    { key: '4' },
    { key: '5' },
    { key: '6' },
    { key: '7' },
    { key: '8' },
    { key: '9' },
    { key: '0' },
    { key: '-' },
    { key: '=' },
    { key: 'Backspace', width: 'large' },
  ],
  [
    { key: 'Tab', width: 'medium' },
    { key: 'Q' },
    { key: 'W' },
    { key: 'E' },
    { key: 'R' },
    { key: 'T' },
    { key: 'Y' },
    { key: 'U' },
    { key: 'I' },
    { key: 'O' },
    { key: 'P' },
    { key: '[' },
    { key: ']' },
    { key: '\\' },
  ],
  [
    { key: 'Caps', width: 'large' },
    { key: 'A' },
    { key: 'S' },
    { key: 'D' },
    { key: 'F', anchor: true },
    { key: 'G' },
    { key: 'H' },
    { key: 'J', anchor: true },
    { key: 'K' },
    { key: 'L' },
    { key: ';' },
    { key: '\'' },
    { key: 'Enter', width: 'large' },
  ],
  [
    { key: 'Shift', width: 'xlarge' },
    { key: 'Z' },
    { key: 'X' },
    { key: 'C' },
    { key: 'V' },
    { key: 'B' },
    { key: 'N' },
    { key: 'M' },
    { key: ',' },
    { key: '.' },
    { key: '/' },
    { key: 'Shift', width: 'xlarge' },
  ],
  [
    { key: 'Space', width: 'space' },
  ],
];